// pages/component/progress/progress.js
Page({
  data:{},
  onLoad:function(){
      console.log('index页面加载')
  },
  onReady:function(){
      console.log('index页面初次渲染完成')
  },
  onShow:function(){
      console.log('index页面显示')
  },
  onHide:function(){
      console.log('index页面隐藏')
  },
  onUnload:function(){
      console.log('index页面卸载')
  }
})